# Generated by Django 4.2.13 on 2024-11-11 21:12

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=600, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1000)],
                        verbose_name="Amount",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Name")),
                (
                    "invite_token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Invite Token"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_owed", models.IntegerField(verbose_name="Amount Owed")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="splitter.expense",
                    ),
                ),
            ],
        ),
    ]
