# Generated by Django 4.2.13 on 2024-11-11 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("splitter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantexpense",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="splitter.group"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="participants",
            field=models.ManyToManyField(
                related_name="expenses",
                through="splitter.ParticipantExpense",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="participantexpense",
            constraint=models.UniqueConstraint(
                fields=("user", "expense"), name="unique_userexpense"
            ),
        ),
    ]
